# Generated by Django 3.1.2 on 2020-10-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
